apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart-monitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart-monitor.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart-monitor.serviceAccountName" . }}
      containers:
        - name: chart-monitor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "chart-monitor.fullname" . }}
            - secretRef:
                name: {{ include "chart-monitor.secretName" . }}
            {{- with .Values.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            - name: ssh-key
              mountPath: {{ .Values.gitops.sshKeyMountPath }}
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "chart-monitor.fullname" . }}-data
        - name: ssh-key
          secret:
            secretName: {{ include "chart-monitor.secretName" . }}
            defaultMode: 0400
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
