apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chart-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart-monitor.labels" . | nindent 4 }}
rules: []
