apiVersion: v2
name: chart-monitor
description: Deploy chart-monitor backend and frontend to Kubernetes and OpenShift
type: application
version: 0.2.0
appVersion: "3.3.0"
keywords:
  - chart-monitor
  - monitoring
  - kubernetes
  - openshift
maintainers:
  - name: chart-monitor maintainers
